Add python extension Fix #12
orozco92/model-to-file pull request #14
Opened 2023-01-23 13:26 UTC by nacastroc

### Description

Adds python extension for exporting models to Python classes. Closes #12. 

### Typing

Python has no explicit typing declaration (though it is a strongly typed language), type hinting is used instead for the base types as the following example:

```python
from typing import Sequence
from datetime import datetime

class Foo:
    
    name: str
    age: int
    birthday: datetime
    salary: float
    toolset: Sequence[Tool]
    active: bool
```

### New Dependencies

Variable and function name casing is converted from _camelCase_ to _snake_case_ as to comply with [PEP 8](https://peps.python.org/pep-0008/), using the [casing](https://www.npmjs.com/package/casing) package.

2023-01-24 07:29 UTC, luismi930213 requested changes

2023-01-24 07:29 UTC, luismi930213 commented on __test__/services/model.service.spec.js
>          expect(fs.existsSync(path.join(__dirname, '..', '..', 'output-models', 'Province.js')))
Te falto poner en el `afterAll` que eliminara el archivo de la carpeta que crea cuando corre los test, como mismo esta el de JS y TS

2023-01-24 07:29 UTC, luismi930213 commented on lib/services/types/python.service.js
> +    classString += '\n'
Porque no pones este salto de linea y el siguiente en la misma linea, algo como `\n class ${modelname}:\n\n`

2023-01-24 07:29 UTC, luismi930213 commented on lib/services/types/python.service.js
> +        classString += `    ${arg}\n`
En todos estos espacios en blanco que asumo que pusiste dando espacio en el teclado usa mejor caracteres especiales como `\t` o similar, es mas legible y menos posibles que alguien cometa el error de borrar un espacio sin querer.

2023-01-24 13:06 UTC, nacastroc commented on lib/services/types/python.service.js
> +    classString += '\n'
Hay dos razones>

1. la primera es legibilidad del código, o sea, trataba de que el código de JS diera una idea de cómo se vería el código Python.
2. La segunda es cumplir con PEP 8, el estándar de estilo de código de Python que dicta dejar una linea en blanco estre los import y las declaraciones de clase, y a su vez entre la declaración de la clase y la declaración de los atributos de clase... etc.

2023-01-24 13:07 UTC, nacastroc commented on lib/services/types/python.service.js
> +        classString += `    ${arg}\n`
Te cabe, voy a probar eso.

2023-01-24 13:10 UTC, nacastroc commented on lib/services/types/python.service.js
> +        classString += `    ${arg}\n`
Hecho. Mejor++

2023-01-24 13:11 UTC, nacastroc commented on __test__/services/model.service.spec.js
>          expect(fs.existsSync(path.join(__dirname, '..', '..', 'output-models', 'Province.js')))
Hecho.

2023-01-25 19:24 UTC, luismi930213 approved these changes

2023-01-25 19:24 UTC, merged