Add usage guide. Fixes #3
orozco92/model-to-file pull request #17
Opened 2023-02-28 04:46 UTC by nacastroc

### Description

Adds usage guide via `-h`, `--help` CLI options. Closes #3.

### New Dependencies

Usage guide display formatting on the console is achieved via the [command-line-usage](https://www.npmjs.com/package/command-line-usage) package.

2023-03-03 13:25 UTC, orozco92 commented on README.md
> +| extension (optional) | e                 | File/language extension for the output class file. Defaults to `.ts`. Supports `ts`, `js`, `py` and `cs`. |
Add php support

2023-03-03 13:58 UTC, orozco92 requested changes

2023-03-03 13:58 UTC, orozco92 commented on README.md
>  | Option               | Alias             | Description                                                         |
Please add help option

2023-03-03 13:58 UTC, orozco92 commented on lib/services/help.service.js
> +                    description: 'File/language extension for the output class file.',
Please add extension support

2023-03-03 13:58 UTC, orozco92 commented on lib/services/help.service.js
> +    const sections = [
It would be nice to have an example section.

2023-03-05 09:24 UTC, luismi930213 approved these changes

2023-03-06 22:49 UTC, orozco92 approved these changes

2023-03-06 22:53 UTC, merged